In [104]:
import numpy as np
import cv2

In [105]:
camera = 1

In [106]:
# reuse extrinsic calibration points for homography
image_points = np.load(f'../extrinsic_calibration_points/{camera}_image.npy')
court_points = np.load(f'../extrinsic_calibration_points/{camera}_world.npy')[:, :2] / 1000
print(image_points)
print(court_points)

[[ 575. 1399.]
 [ 859.  905.]
 [ 955.  747.]
 [1032.  623.]
 [1147.  443.]
 [2722. 1432.]
 [2445.  934.]
 [2354.  774.]
 [2281.  648.]
 [2171.  462.]]
[[ 0.  0.]
 [ 6.  0.]
 [ 9.  0.]
 [12.  0.]
 [18.  0.]
 [ 0.  9.]
 [ 6.  9.]
 [ 9.  9.]
 [12.  9.]
 [18.  9.]]


In [107]:
homography_matrix, _ = cv2.findHomography(image_points, court_points)
print(homography_matrix)

[[ 6.03795596e-04 -3.61226263e-02  5.00950299e+01]
 [ 1.67301152e-02  1.02325084e-02 -2.36944940e+01]
 [-4.91331791e-05  2.24013621e-03  1.00000000e+00]]


In [108]:
np.save(f'../homography_matrices/{camera}', homography_matrix)

In [109]:
# test_image = np.array([1482, 966, 1])
# test_court = np.dot(homography_matrix, test_image)
# print(test_court / test_court[2])

In [110]:
# test_court = [6, -1.75, 1]
# test_image = np.dot(np.linalg.inv(homography_matrix), test_court)
# print(test_image / test_image[2])